"""initial schema — all existing AstroGraph tables and indexes

Revision ID: 104e71dd8a46
Revises:
Create Date: 2026-04-06

NOTE: For existing databases, run:
  alembic stamp 104e71dd8a46
to mark the current DB state as this baseline. Subsequent
changes can then be autogenerated with --autogenerate.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "104e71dd8a46"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all existing AstroGraph tables and indexes."""

    # ── users ────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("salt", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )

    # ── qa_history ───────────────────────────────────────────────────────────
    op.create_table(
        "qa_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("citations_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_qa_history_user_id", "qa_history", ["user_id", "id"], unique=False)

    # ── auth_tokens ────────────────────────────────────────────────────────
    op.create_table(
        "auth_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index("idx_auth_tokens_user_id", "auth_tokens", ["user_id"], unique=False)

    # ── knowledge_chunks ───────────────────────────────────────────────────
    op.create_table(
        "knowledge_chunks",
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("source_file", sa.String(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_index("idx_knowledge_chunks_category", "knowledge_chunks", ["category"], unique=False)
    op.create_index("idx_knowledge_chunks_source", "knowledge_chunks", ["source_file"], unique=False)

    # ── image_assets ───────────────────────────────────────────────────────
    op.create_table(
        "image_assets",
        sa.Column("image_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("ref", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("object_keys_json", sa.Text(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("image_id"),
    )
    op.create_index("idx_image_assets_title", "image_assets", ["title"], unique=False)
    op.create_index("idx_image_assets_kind", "image_assets", ["kind"], unique=False)


def downgrade() -> None:
    """Drop all tables (irreversible)."""
    op.drop_table("image_assets")
    op.drop_table("knowledge_chunks")
    op.drop_table("auth_tokens")
    op.drop_table("qa_history")
    op.drop_table("users")
